Adjust run no requirement and in debug mode call correct lut sim (TrigT1CaloMonitoring-00-14-40)
  * Adjust required run number for run 2 lut simulation
  * Fix calling correct lut simulation in debug mode
  * Tag as TrigT1CaloMonitoring-00-14-40

2015-06-01 Alexander Mazurov <alexander.mazurov@cern.ch>
  * TrigT1CaloMonitoring_forRecExCommission_Run1.py:
    - fix ATR-11347 (AttributeError: 'LVL1__PPrStabilityMon' object has no attribute 'BS_TriggerTowerContainer')
  * Tag as TrigT1CaloMonitoring-00-14-39

2015-05-28 Veit Scharf <veit.scharf@kip.uni-heidelberg.de>
  * try to circumvent Coverity issue 30063
  * Tag as TrigT1CaloMonitoring-00-14-38