EventLoopGrid: minor changes for R22 AnalysisBase
Hello,

This MR is tentatively fixing 2 EventLoopGrid-related errors seen when submitting GRID jobs with AnalysisBase 22.2.0:
```
TUnixSystem::GetFromPipe  ERROR   command "python -c "from pandatools import PsubUtils;print PsubUtils.getNickname();" 2>/dev/null" returned 256
```
and
```
  File "<string>", line 130, in ELG_prun
  File "/cvmfs/atlas.cern.ch/repo/sw/software/22.2/AnalysisBaseExternals/22.2.0/InstallArea/x86_64-centos7-gcc8-opt/lib/python3.7/re.py", line 223, in findall
    return _compile(pattern, flags).findall(string)
TypeError: cannot use a string pattern on a bytes-like object
TypeError: an integer is required (got type NoneType)
```

The job submission is "successful" with the proposed changes (well, jobs crash at runtime, but likely due to an unrelated reason...).

Tagging Nils for verification.

Cheers,
Bertrand